char* StrChr(const char* str, int ch);
size_t StrLen(const char* str);
int StrCmp(const char* str1, const char* str2);
int StrnCmp(const char* str1, const char* str2, size_t n);
int StrCaseCmp(const char* str1, const char* str2);
char* StrCpy(char* dest, const char* src);
char* StrnCpy(char* dest, const char* src, size_t n);
char* StrDup(const char* str);
char* StrCat(char* dst, const char* src);
char* StrnCat(char* dst, const char* src, size_t ssize);
char* StrStr(const char* haystack, const char *needle);
size_t StrSpn_oops(const char* str, const char* accept);
size_t StrSpn(const char* str, const char* accept);
int IsPalindrome(const char* str);
char* SpaceReview(char* str);
